name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Roswell
      env:
        LISP: ${{ matrix.lisp }}
      run: |
        curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
    - name: Run test
      run: |
        export PATH=$HOME/.roswell/bin:$PATH
        ros install cxxxr/sblint
        ros -s rove -s lisp-reviewer -s lisp-reviewer/test -e '(uiop:quit (if (rove:run :lisp-reviewer/test) 0 1))'
